#!/bin/bash
export mycluster=ocp47
export vmdir=/VirtualMachines/VMs
NAME=${1}
./add_node.sh --name ${NAME} \
  --cpu 16 \
  --memory 16000 \
  --add-disk 100 \
  --add-disk 500 \
  --vm-dir ${vmdir}/${mycluster} \
  --libvirt-network default
