#!/bin/bash
export mycluster=ocp47
export vmdir=/VirtualMachines/VMs
mkdir -p ${vmdir}/${mycluster}

./ocp4_setup_upi_kvm.sh --yes --keep-bootstrap --destroy \
 --ocp-version 4.7 \
 --pull-secret pull-secret/pull-secret.txt \
 --cluster-name ${mycluster} \
 --lb-mem 4096 \
 --libvirt-network default \
 --vm-dir ${vmdir}/${mycluster} \
 --setup-dir ${mycluster}_setup \
 --cache-dir ${vmdir}/ISOs \
 --masters 3 \
 --master-cpu 4 \
 --master-mem 16000 \
 --workers 3 \
 --worker-cpu 8 \
 --worker-mem 16000 \
 --dns-dir /etc/NetworkManager/dnsmasq.d \
 --fresh-download

for vm in $(virsh list --name | grep ${mycluster})
do
   virsh destroy ${vm}
   virsh undefine ${vm}
done
